services:
  coj-backend-gateway:
    container_name: coj-backend-gateway
    image: moriic/coj-backend-gateway
    ports:
      - "8101:8101"
    networks:
      - mynetwork
  coj-backend-user-service:
    container_name: coj-backend-user-service
    ports:
      - "8102:8102"
    image: moriic/coj-backend-user-service
    depends_on:
      - coj-backend-gateway
    networks:
      - mynetwork
  coj-backend-question-service:
    container_name: coj-backend-question-service
    image: moriic/coj-backend-question-service
    ports:
      - "8103:8103"
    depends_on:
      - coj-backend-user-service
      - coj-backend-gateway
    networks:
      - mynetwork
  coj-backend-judge-service:
    container_name: coj-backend-judge-service
    image: moriic/coj-backend-judge-service
    ports:
      - "8104:8104"
    depends_on:
      - coj-backend-user-service
      - coj-backend-question-service
      - coj-backend-gateway
    networks:
      - mynetwork
networks:
  mynetwork: