spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://coj-mysql:3306/coj
    username: root
    password: qq1219533124.
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: coj-nacos:8848
  rabbitmq:
    host: coj-rabbitmq
    port: 5672
    username: moriic
    password: qq1219533124.
